name: Deploy Remotely

on:
  push:
    branches: [ main ]
jobs:
  Deploy-Remotely:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install Dependencies and Build Locally
      run: |
        npm ci --production --force
        npm run build

    - name: Transfer Build Artifacts to EC2
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
        REMOTE_USER: ${{ secrets.DEPLOY_USER }}
        REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
        SOURCE: "build"  # Replace 'build' with the folder containing your output files
        TARGET: ${{ secrets.DEPLOY_TARGET }}

    - name: Restart Application on EC2
      run: |
        echo "${{ secrets.DEPLOY_KEY }}" > deploy_key.pem
        chmod 400 deploy_key.pem
        ssh -o StrictHostKeyChecking=no -i "deploy_key.pem" -p ${{ secrets.DEPLOY_PORT }} ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "
          pm2 reload new-app
        "
        rm deploy_key.pem

