name: Deploy Remotely

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  Deploy-Remotely:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Node.js Environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    # Step 3: Install Dependencies
    - name: Install Dependencies
      run: npm install

    # Step 4: Build the Project
    - name: Build Project
      run: npm run build

    # Step 5: Transfer Build Output to EC2 Instance
    - name: Transfer Folder to EC2 Instance
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
        REMOTE_USER: ${{ secrets.DEPLOY_USER }}
        REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
        SOURCE: "./.next"  # Adjust if necessary for your build output
        TARGET: ${{ secrets.DEPLOY_TARGET }}
